/*********************************************************
 **
 ** File  aol_line_width_table.c
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.4b (build i9)
 **
 ** Date of generation: 2018-01-27T10:54:04
 ** Command line: D:\Program Files\ANSYS Inc\v182\SCADE\SCADE Display\KCG66\bin/ScadeDisplayKCG.exe -outdir F:\TestPrj\TestScade\kcg F:\TestPrj\TestScade\line_width_table.swt
 *********************************************************/

#include "aol_line_width_table.h"

/* Line width table definition */
const sgl_line_width aol_line_width_table[aol_line_width_table_size] = 
{
{ 1.2F,             1.5F,             3.F              }, /* 0 : LW0 */
{ 2.5F,             1.5F,             3.5F             }, /* 1 : LW1 */
{ 3.5F,             2.5F,             4.2F             }, /* 2 : LW2 */
{ 4.5F,             3.5F,             5.5F             }, /* 3 : LW3 */
{ 5.5F,             4.5F,             6.5F             }, /* 4 : LW4 */
{ 6.5F,             5.5F,             7.5F             }, /* 5 : LW5 */
{ 7.5F,             6.5F,             8.5F             }, /* 6 : LW6 */
{ 8.5F,             7.5F,             9.5F             }  /* 7 : LW7 */
};

/*********************************************************
 ** End of file
 ** End of generation: 2018-01-27T10:54:04
 *********************************************************/

