/*********************************************************
 **
 ** File  aol_line_stipple_table.c
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.4b (build i9)
 **
 ** Date of generation: 2018-01-27T10:54:05
 ** Command line: D:\Program Files\ANSYS Inc\v182\SCADE\SCADE Display\KCG66\bin/ScadeDisplayKCG.exe -outdir F:\TestPrj\TestScade\kcg F:\TestPrj\TestScade\line_stipple_table.sst
 *********************************************************/

#include "aol_line_stipple_table.h"

/* Line stipple table definition */
const sgl_linestipple aol_line_stipple_table[aol_line_stipple_table_size] = 
{
{ {   0U,   0U,   0U,   0U,   0U,   0U}, {   0U,   0U,   0U,   0U,   0U,   0U},   1U,   0U}, /* 0 solid pattern :  */
{ {  12U,  12U,   0U,   0U,   0U,   0U}, {   1U,   0U,   0U,   0U,   0U,   0U},   0U,   2U}, /* 1 dashed pattern :  */
{ {   8U,   8U,   0U,   0U,   0U,   0U}, {   1U,   0U,   0U,   0U,   0U,   0U},   0U,   2U}, /* 2 dashed pattern :  */
{ {   1U,   6U,   0U,   0U,   0U,   0U}, {   1U,   0U,   0U,   0U,   0U,   0U},   0U,   2U}, /* 3 dashed pattern :  */
{ {   1U,   8U,   8U,   8U,   0U,   0U}, {   1U,   0U,   1U,   0U,   0U,   0U},   0U,   4U}  /* 4 dashed pattern :  */
};

/*********************************************************
 ** End of file
 ** End of generation: 2018-01-27T10:54:05
 *********************************************************/

