/*********************************************************
 **
 ** File  aol_symbology_layer.c
 **
 ** Specification File:  F:\TestPrj\TestScade\specification.sgfx
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.4b (build i9)
 **
 ** Date of generation: 2018-01-27T10:54:10
 ** Command line: ScadeDisplayKCG.exe -outdir F:\TestPrj\TestScade\kcg -texturemax 1024 F:\TestPrj\TestScade\specification.sgfx
 *********************************************************/

#include "aol_symbology_layer.h"
#include "aol_imported_functions.h"
#include "sgl.h"


void aol_symbology_layer_init(aol_typ_symbology_layer *pContext)
{

}

void aol_symbology_layer_predraw(aol_typ_symbology_layer *pContext)
{

}

void aol_symbology_layer_draw(aol_typ_symbology_layer *pContext, SGLint32 pPriority)
{
  if (SGLint32_eq(pPriority, 0L)) {

    /* Object: symbology_layer, Type: layer, OID: 456ac681-69ff-46c6-a3b6-52e329a065c0 */
    {
      sglPushMatrixAndTranslate(1024.0F, 768.0F);

      /* Object: rectangle, Type: rectangle, OID: 6892852e-34d4-41eb-a353-2b93e2cedd77 */
      {
        sglSetActiveMasks(SGL_NO_MASK);
        /* outline object part */
        sglDisable(SGL_TEXTURE_2D);
        sglIndexColori(32L);
        sglIndexHaloColori(-1L);
        sglIndexLineWidthi(2L);
        sglIndexLineStipplei(0L);
        sglDisable(SGL_LINE_HALOING);
        sglSetLineCaps(SGL_ROUNDED_CAPS);
        sglTransparency8(255L);
        sglBegin(SGL_LINE_LOOP);
        sglVertex2f(-1024.0F, 768.0F);
        sglVertex2f(1024.0F, 768.0F);
        sglVertex2f(1024.0F, -768.0F);
        sglVertex2f(-1024.0F, -768.0F);
        sglEnd();
      }

      /* Object: circle, Type: circle, OID: 9422bbaa-cc31-4878-8d35-f3decc3c9855 */
      {
        /* outline object part */
        sgluArcSector2f(-4.0F, 0.0F, 656.219475F, 0.0F, 360.0F, SGL_TRUE, SGL_ARC_CIRCLE_LINE);
      }
      sglPopMatrixAndTranslate();
    }
  }
}


/*********************************************************
 ** End of file
 ** End of generation: 2018-01-27T10:54:10
 *********************************************************/

