/*********************************************************
 **
 ** File  aol_texture_table.c
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.4b (build i9)
 **
 ** Date of generation: 2017-12-23T17:23:50
 ** Command line: D:\Program Files\ANSYS Inc\v182\SCADE\SCADE Display\KCG66\bin/ScadeDisplayKCG.exe -outdir F:\TestScade\TestScad\specification_Code F:\TestScade\TestScad\texture_table.stt
 *********************************************************/

#include "sgl.h"
#include "aol_texture_table.h"

/* Textures definition */
void aol_texture_table(void)
{

}

/*********************************************************
 ** End of file
 ** End of generation: 2017-12-23T17:23:50
 *********************************************************/

