/*********************************************************
 **
 ** File  aol_imported_functions.h
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.4b (build i9)
 **
 ** Date of generation: 2018-01-27T10:54:10
 ** Command line: ScadeDisplayKCG.exe -outdir F:\TestPrj\TestScade\kcg -texturemax 1024 F:\TestPrj\TestScade\specification.sgfx
 *********************************************************/

#ifndef AOL_IMPORTED_FUNCTIONS_H
#define AOL_IMPORTED_FUNCTIONS_H

#include "sgl_types.h"

/* Imported functions */

#endif /* AOL_IMPORTED_FUNCTIONS_H */

/*********************************************************
 ** End of file
 ** End of generation: 2018-01-27T10:54:10
 *********************************************************/

