/*********************************************************
 **
 ** File  aol_imported_functions.h
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.4b (build i9)
 **
 ** Date of generation: 2018-01-11T19:05:53
 ** Command line: ScadeDisplayKCG.exe -outdir E:\AndroidStudioProjects\ScadeDisplay\arj_iOS\CodeSDY -prefix aol_ -texturemax 1024 E:\AndroidStudioProjects\ScadeDisplay\arj.sgfx E:\AndroidStudioProjects\ScadeDisplay\texture_table.stt E:\AndroidStudioProjects\ScadeDisplay\font_table.sft E:\AndroidStudioProjects\ScadeDisplay\color_table.sct E:\AndroidStudioProjects\ScadeDisplay\line_width_table.swt E:\AndroidStudioProjects\ScadeDisplay\line_stipple_table.sst
 *********************************************************/

#ifndef AOL_IMPORTED_FUNCTIONS_H
#define AOL_IMPORTED_FUNCTIONS_H

#include "sgl_types.h"

/* Imported functions */

#endif /* AOL_IMPORTED_FUNCTIONS_H */

/*********************************************************
 ** End of file
 ** End of generation: 2018-01-11T19:05:53
 *********************************************************/

