/*********************************************************
 **
 ** File  aol_font_table.h
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.4b (build i9)
 **
 ** Date of generation: 2018-01-27T10:54:08
 ** Command line: D:\Program Files\ANSYS Inc\v182\SCADE\SCADE Display\KCG66\bin/ScadeDisplayKCG.exe -outdir F:\TestPrj\TestScade\kcg F:\TestPrj\TestScade\font_table.sft
 *********************************************************/

#ifndef AOL_FONT_TABLE_H
#define AOL_FONT_TABLE_H

#include "glf.h"

/* Fonts definition */

typedef struct
{
  glf_type_font_table_header tr_header;
  glf_type_font tr_fonts_description[13UL];
  glf_type_map_property tr_maps[3UL];
  glf_type_character_bitmap5 tr_characters0[101UL];
  glf_type_character_bitmap5 tr_characters1[101UL];
  glf_type_character_bitmap6 tr_characters2[101UL];
  glf_type_character_bitmap6 tr_characters3[101UL];
  glf_type_character_bitmap7 tr_characters4[101UL];
  glf_type_character_bitmap2 tr_characters5[475UL];
  glf_type_character_bitmap2 tr_characters6[475UL];
  glf_type_character_bitmap2 tr_characters7[475UL];
  glf_type_character_bitmap2 tr_characters8[475UL];
  glf_type_character_bitmap2 tr_characters9[366UL];
  glf_type_character_bitmap2 tr_characters10[366UL];
  glf_type_character_bitmap2 tr_characters11[366UL];
  glf_type_character_bitmap2 tr_characters12[366UL];
} aol_font_table_type;

extern SGLuint8 aol_font_table_texture0[530829UL];
extern SGLuint8 aol_font_table_texture1[500001UL];
extern SGLuint8 aol_font_table_texture2[449612UL];

extern const aol_font_table_type aol_font_table;

#endif /* AOL_FONT_TABLE_H */

/*********************************************************
 ** End of file
 ** End of generation: 2018-01-27T10:54:08
 *********************************************************/

