/*********************************************************
 **
 ** File  aol_color_table.h
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.4b (build i9)
 **
 ** Date of generation: 2018-01-27T10:54:03
 ** Command line: D:\Program Files\ANSYS Inc\v182\SCADE\SCADE Display\KCG66\bin/ScadeDisplayKCG.exe -outdir F:\TestPrj\TestScade\kcg F:\TestPrj\TestScade\color_table.sct
 *********************************************************/

#ifndef AOL_COLOR_TABLE_H
#define AOL_COLOR_TABLE_H

#include "sgl_types.h"

/* Color table definition */

#define aol_color_table_size 128UL

extern const sgl_color aol_color_table[aol_color_table_size];

#define aol_color_table_background_index 1UL

#endif /* AOL_COLOR_TABLE_H */

/*********************************************************
 ** End of file
 ** End of generation: 2018-01-27T10:54:03
 *********************************************************/

