/*********************************************************
 **
 ** File  aol_texture_table.h
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.4b (build i9)
 **
 ** Date of generation: 2017-12-23T17:23:50
 ** Command line: D:\Program Files\ANSYS Inc\v182\SCADE\SCADE Display\KCG66\bin/ScadeDisplayKCG.exe -outdir F:\TestScade\TestScad\specification_Code F:\TestScade\TestScad\texture_table.stt
 *********************************************************/

#ifndef AOL_TEXTURE_TABLE_H
#define AOL_TEXTURE_TABLE_H

#include "sgl_types.h"

/* Textures definition */

#define aol_texture_table_size 0UL

extern void aol_texture_table(void);

#endif /* AOL_TEXTURE_TABLE_H */

/*********************************************************
 ** End of file
 ** End of generation: 2017-12-23T17:23:50
 *********************************************************/

