/*********************************************************
 **
 ** File  aol_line_width_table.h
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.4b (build i9)
 **
 ** Date of generation: 2018-01-27T10:54:04
 ** Command line: D:\Program Files\ANSYS Inc\v182\SCADE\SCADE Display\KCG66\bin/ScadeDisplayKCG.exe -outdir F:\TestPrj\TestScade\kcg F:\TestPrj\TestScade\line_width_table.swt
 *********************************************************/

#ifndef AOL_LINE_WIDTH_TABLE_H
#define AOL_LINE_WIDTH_TABLE_H

#include "sgl_types.h"

/* Line width table definition */

#define aol_line_width_table_size 8UL

extern const sgl_line_width aol_line_width_table[aol_line_width_table_size];

#endif /* AOL_LINE_WIDTH_TABLE_H */

/*********************************************************
 ** End of file
 ** End of generation: 2018-01-27T10:54:04
 *********************************************************/

