/*********************************************************
 **
 ** File  aol_color_table.h
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.4b (build i9)
 **
 ** Date of generation: 2018-01-11T19:05:53
 ** Command line: ScadeDisplayKCG.exe -outdir E:\AndroidStudioProjects\ScadeDisplay\arj_iOS\CodeSDY -prefix aol_ -texturemax 1024 E:\AndroidStudioProjects\ScadeDisplay\arj.sgfx E:\AndroidStudioProjects\ScadeDisplay\texture_table.stt E:\AndroidStudioProjects\ScadeDisplay\font_table.sft E:\AndroidStudioProjects\ScadeDisplay\color_table.sct E:\AndroidStudioProjects\ScadeDisplay\line_width_table.swt E:\AndroidStudioProjects\ScadeDisplay\line_stipple_table.sst
 *********************************************************/

#ifndef AOL_COLOR_TABLE_H
#define AOL_COLOR_TABLE_H

#include "sgl_types.h"

/* Color table definition */

#define aol_color_table_size 128UL

extern const sgl_color aol_color_table[aol_color_table_size];

#define aol_color_table_background_index 1UL

#endif /* AOL_COLOR_TABLE_H */

/*********************************************************
 ** End of file
 ** End of generation: 2018-01-11T19:05:53
 *********************************************************/

