/*********************************************************
 **
 ** File  aol_line_stipple_table.h
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.4b (build i9)
 **
 ** Date of generation: 2018-01-27T10:54:05
 ** Command line: D:\Program Files\ANSYS Inc\v182\SCADE\SCADE Display\KCG66\bin/ScadeDisplayKCG.exe -outdir F:\TestPrj\TestScade\kcg F:\TestPrj\TestScade\line_stipple_table.sst
 *********************************************************/

#ifndef AOL_LINE_STIPPLE_TABLE_H
#define AOL_LINE_STIPPLE_TABLE_H

#include "sgl_types.h"

/* Line stipple table definition */

#define aol_line_stipple_table_size 5UL

extern const sgl_linestipple aol_line_stipple_table[aol_line_stipple_table_size];

#endif /* AOL_LINE_STIPPLE_TABLE_H */

/*********************************************************
 ** End of file
 ** End of generation: 2018-01-27T10:54:05
 *********************************************************/

