/*********************************************************
 **
 ** File  aol_line_stipple_table.c
 **
 ** Automatically generated by SCADE Display KCG
 ** Version 6.6.4b (build i9)
 **
 ** Date of generation: 2018-01-11T19:05:53
 ** Command line: ScadeDisplayKCG.exe -outdir E:\AndroidStudioProjects\ScadeDisplay\arj_iOS\CodeSDY -prefix aol_ -texturemax 1024 E:\AndroidStudioProjects\ScadeDisplay\arj.sgfx E:\AndroidStudioProjects\ScadeDisplay\texture_table.stt E:\AndroidStudioProjects\ScadeDisplay\font_table.sft E:\AndroidStudioProjects\ScadeDisplay\color_table.sct E:\AndroidStudioProjects\ScadeDisplay\line_width_table.swt E:\AndroidStudioProjects\ScadeDisplay\line_stipple_table.sst
 *********************************************************/

#include "aol_line_stipple_table.h"

/* Line stipple table definition */
const sgl_linestipple aol_line_stipple_table[aol_line_stipple_table_size] = 
{
{ {   0U,   0U,   0U,   0U,   0U,   0U}, {   0U,   0U,   0U,   0U,   0U,   0U},   1U,   0U}, /* 0 solid pattern :  */
{ {  12U,  12U,   0U,   0U,   0U,   0U}, {   1U,   0U,   0U,   0U,   0U,   0U},   0U,   2U}, /* 1 dashed pattern :  */
{ {   8U,   8U,   0U,   0U,   0U,   0U}, {   1U,   0U,   0U,   0U,   0U,   0U},   0U,   2U}, /* 2 dashed pattern :  */
{ {   1U,   6U,   0U,   0U,   0U,   0U}, {   1U,   0U,   0U,   0U,   0U,   0U},   0U,   2U}, /* 3 dashed pattern :  */
{ {   1U,   8U,   8U,   8U,   0U,   0U}, {   1U,   0U,   1U,   0U,   0U,   0U},   0U,   4U}  /* 4 dashed pattern :  */
};

/*********************************************************
 ** End of file
 ** End of generation: 2018-01-11T19:05:53
 *********************************************************/

