
/* Code generated by SCADE Display Adaptor */


#include "arj_display_adaptor.h"

/* Contexts for SCADE Display KCG Code */

#include "aol_symbology_layer.h"
aol_typ_symbology_layer symbology_layer_ctx;
aol_typ_symbology_layer* p_symbology_layer_ctx = &symbology_layer_ctx;



/* Reset function */

void Reset(void){
	/* Reset SCADE Display KCG outputs */
	aol_symbology_layer_init(p_symbology_layer_ctx);
}

/* Step function */

void Step(void){
	BHVR_SetAsynchronousACK();

	/* Perform SCADE Display drawings */
	aol_symbology_layer_predraw(p_symbology_layer_ctx);
	aol_symbology_layer_draw(p_symbology_layer_ctx, 0);
	aol_symbology_layer_draw(p_symbology_layer_ctx, 1);
	aol_symbology_layer_draw(p_symbology_layer_ctx, 2);
	aol_symbology_layer_draw(p_symbology_layer_ctx, 3);
	aol_symbology_layer_draw(p_symbology_layer_ctx, 4);
	aol_symbology_layer_draw(p_symbology_layer_ctx, 5);
	aol_symbology_layer_draw(p_symbology_layer_ctx, 6);
	aol_symbology_layer_draw(p_symbology_layer_ctx, 7);

}

