
/* Code generated by SCADE Display Adaptor */

#ifndef DISPLAY_ADAPTOR
#define DISPLAY_ADAPTOR

/* Declarations of Reset and Step functions */
extern void Reset(void);
extern void Step(void);
extern void BHVR_SetAsynchronousACK(void);

/* Declarations of connections functions called inside Reset and Step */

#endif /* DISPLAY_ADAPTOR */
