/* Generated by SCADE Display */

#ifndef __TARGET_CONFIGURATION_H__
#define __TARGET_CONFIGURATION_H__

#include "sglConstants.h"
#include "sgl_types.h"

extern unsigned long target_screen_width;
extern unsigned long target_screen_height;
extern const double ratio_x;
extern const double ratio_y;
extern const long target_periodicity;
extern const char *specification_name;

#define MAX_POINTERS 5
#define MAX_KEYBOARDS 1

#endif

