/* Generated by SCADE Display */


#include "target_configuration.h"

unsigned long target_screen_width = 1280;
unsigned long target_screen_height = 1024;
const double ratio_x = 0.027344;
const double ratio_y = 0.027344;
const long target_periodicity = 33;
const char *specification_name = "arj";

